In [2]:
#initial - import some basic libraries that might be useful here
%pylab inline
import pandas as pd
import seaborn as sns
pd.set_option('display.max_rows', 30)
import numpy as np

Populating the interactive namespace from numpy and matplotlib

In [3]:
#read the CSV file part 1
data = pd.read_csv("https://raw.githubusercontent.com/Nancyxw/AI_Final_Project/master/updated_fulltext.csv",index_col = 0)
df1 = pd.DataFrame(data)
df1.shape

(1109, 32)

In [4]:
#read the CSV file part 2
data = pd.read_csv("https://raw.githubusercontent.com/Nancyxw/AI_Final_Project/master/updated_fulltext2.csv",index_col = 0)
df2 = pd.DataFrame(data)
df2.shape

(1464, 32)

In [5]:
#merge the two dataframe
df = df1.merge(df2,how = 'outer')
df.head()

,_id,contributors,coordinates,created_at,display_text_range,entities,extended_entities,favorite_count,favorited,full_text,...,possibly_sensitive,quoted_status,quoted_status_id,quoted_status_id_str,retweet_count,retweeted,retweeted_status,source,truncated,user
0,5a352ea10a411836947f6c28,NaN,NaN,Fri Dec 15 19:18:49 +0000 2017,"[0, 96]","{'hashtags': [{'text': 'Microsoft', 'indices':...",NaN,0,False,#Microsoft adds more #AI smarts to #Office365 ...,...,False,NaN,NaN,NaN,0,False,NaN,"<a href=""http://twitter.com/download/android"" ...",False,"{'id': 118809265, 'id_str': '118809265', 'name..."
1,5a352e9e0a411836947f6c0f,NaN,NaN,Fri Dec 15 23:41:58 +0000 2017,"[0, 140]","{'hashtags': [{'text': 'AI', 'indices': [56, 5...",NaN,0,False,RT @MSFTResearch: “As the first generation to ...,...,NaN,NaN,NaN,NaN,136,False,{'created_at': 'Wed Dec 13 22:25:52 +0000 2017...,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 214472493, 'id_str': '214472493', 'name..."
2,5a352e9f0a411836947f6c10,NaN,NaN,Fri Dec 15 23:36:50 +0000 2017,"[0, 140]","{'hashtags': [{'text': 'healthcare', 'indices'...",NaN,0,False,RT @MSFTResearch: Microsoft’s Healthcare NExT ...,...,NaN,NaN,NaN,NaN,27,False,{'created_at': 'Thu Dec 14 01:04:16 +0000 2017...,"<a href=""http://www.twitter.com"" rel=""nofollow...",False,"{'id': 42980514, 'id_str': '42980514', 'name':..."
3,5a352e9f0a411836947f6c11,NaN,NaN,Fri Dec 15 23:34:27 +0000 2017,"[0, 140]","{'hashtags': [{'text': 'healthcare', 'indices'...",NaN,0,False,RT @MSFTResearch: Microsoft’s Healthcare NExT ...,...,NaN,NaN,NaN,NaN,27,False,{'created_at': 'Thu Dec 14 01:04:16 +0000 2017...,"<a href=""http://www.twitter.com"" rel=""nofollow...",False,"{'id': 75866694, 'id_str': '75866694', 'name':..."
4,5a352e9f0a411836947f6c12,NaN,NaN,Fri Dec 15 23:10:23 +0000 2017,"[0, 140]","{'hashtags': [{'text': 'healthcare', 'indices'...",NaN,0,False,RT @MSFTResearch: Microsoft’s Healthcare NExT ...,...,NaN,NaN,NaN,NaN,27,False,{'created_at': 'Thu Dec 14 01:04:16 +0000 2017...,"<a href=""http://twitter.com/download/iphone"" r...",False,"{'id': 14707761, 'id_str': '14707761', 'name':..."

In [20]:
clean_df = df[['created_at','display_text_range','full_text','favorite_count','retweeted_status','retweet_count',]]
clean_df.head(2)

,created_at,display_text_range,full_text,favorite_count,retweeted_status,retweet_count
0,Fri Dec 15 19:18:49 +0000 2017,"[0, 96]",#Microsoft adds more #AI smarts to #Office365 ...,0,NaN,0
1,Fri Dec 15 23:41:58 +0000 2017,"[0, 140]",RT @MSFTResearch: “As the first generation to ...,0,{'created_at': 'Wed Dec 13 22:25:52 +0000 2017...,136

In [21]:
#update the text number
text_number = []
for i in clean_df['display_text_range']:
    text_number.append(i.split(',')[1][:-1])

clean_df['text_number'] = text_number
clean_df = clean_df.drop(['display_text_range'], axis = 1)
clean_df.head(2)

D:\PythonSoftware\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,created_at,full_text,favorite_count,retweeted_status,retweet_count,text_number
0,Fri Dec 15 19:18:49 +0000 2017,#Microsoft adds more #AI smarts to #Office365 ...,0,NaN,0,96
1,Fri Dec 15 23:41:58 +0000 2017,RT @MSFTResearch: “As the first generation to ...,0,{'created_at': 'Wed Dec 13 22:25:52 +0000 2017...,136,140

In [22]:
#binary - retweet result
retweet_stat = []
for i in clean_df['retweet_count']:
    if i == 0:
        retweet_stat.append(0)
    else:
        retweet_stat.append(1)
clean_df['being retweeted(0/1)']= retweet_stat
clean_df.head(2)

,created_at,full_text,favorite_count,retweeted_status,retweet_count,text_number,being retweeted(0/1)
0,Fri Dec 15 19:18:49 +0000 2017,#Microsoft adds more #AI smarts to #Office365 ...,0,NaN,0,96,0
1,Fri Dec 15 23:41:58 +0000 2017,RT @MSFTResearch: “As the first generation to ...,0,{'created_at': 'Wed Dec 13 22:25:52 +0000 2017...,136,140,1

In [23]:
clean_df.head(2)

,created_at,full_text,favorite_count,retweeted_status,retweet_count,text_number,being retweeted(0/1)
0,Fri Dec 15 19:18:49 +0000 2017,#Microsoft adds more #AI smarts to #Office365 ...,0,NaN,0,96,0
1,Fri Dec 15 23:41:58 +0000 2017,RT @MSFTResearch: “As the first generation to ...,0,{'created_at': 'Wed Dec 13 22:25:52 +0000 2017...,136,140,1